### ISSUE TITLE
[express-apollo-prisma] Stopping the script `queue:run` causes an error

### ISSUE THREAD

**Issue by mbicknese** [thisdot/starter.dev#1138]
### Stack

OS: *MacOS 13.1*
Shell: *zsh*
Node: *16.17.0*

### Steps

1. Run `pnpm install`
2. Ensure there is a valid configuration (for example, by copying `.env.example` to `.env`)
3. Run `pnpm infrastructure:start`
4. Run `pnpm run queue:run`
5. Press [ctrl] + [c]

## Expected behaviour

All services started by the command should gracefully stop again. No errors should be shown in the terminal output, and the exit code should be 0.

## Actual behaviour

The command stops with the message:

```
ELIFECYCLE  Command failed with exit code 1.
```

With exit code `1`

### Log

```
> express-apollo-prisma@0.0.1 queue:run /Users/maarten/ThisDot/starter.dev/starters/express-apollo-prisma
> ts-node queue/worker.ts

Listening queue: "jobs" ...
^C/Users/maarten/ThisDot/starter.dev/starters/express-apollo-prisma/node_modules/.pnpm/amqplib@0.10.3/node_modules/amqplib/lib/channel.js:159
    throw new IllegalOperationError(msg, stack);
          ^
IllegalOperationError: Channel closing
    at Channel.<anonymous> (/Users/maarten/ThisDot/starter.dev/starters/express-apollo-prisma/node_modules/.pnpm/amqplib@0.10.3/node_modules/amqplib/lib/channel.js:159:11)
    at Channel.C.closeBecause (/Users/maarten/ThisDot/starter.dev/starters/express-apollo-prisma/node_modules/.pnpm/amqplib@0.10.3/node_modules/amqplib/lib/channel.js:211:8)
    at /Users/maarten/ThisDot/starter.dev/starters/express-apollo-prisma/node_modules/.pnpm/amqplib@0.10.3/node_modules/amqplib/lib/channel_model.js:72:19
    at node:internal/util:361:7
    at new Promise (<anonymous>)
    at node:internal/util:347:12
    at Channel.close (/Users/maarten/ThisDot/starter.dev/starters/express-apollo-prisma/node_modules/.pnpm/amqplib@0.10.3/node_modules/amqplib/lib/channel_model.js:74:7)
    at /Users/maarten/ThisDot/starter.dev/starters/express-apollo-prisma/queue/worker.ts:33:17
    at Generator.next (<anonymous>) {
  stackAtStateChange: 'Stack capture: closeBecause called: Goodbye\n' +
    '    at Channel.C.closeBecause (/Users/maarten/ThisDot/starter.dev/starters/express-apollo-prisma/node_modules/.pnpm/amqplib@0.10.3/node_modules/amqplib/lib/channel.js:216:11)\n' +
    '    at /Users/maarten/ThisDot/starter.dev/starters/express-apollo-prisma/node_modules/.pnpm/amqplib@0.10.3/node_modules/amqplib/lib/channel_model.js:72:19\n' +
    '    at node:internal/util:361:7\n' +
    '    at new Promise (<anonymous>)\n' +
    '    at node:internal/util:347:12\n' +
    '    at Channel.close (/Users/maarten/ThisDot/starter.dev/starters/express-apollo-prisma/node_modules/.pnpm/amqplib@0.10.3/node_modules/amqplib/lib/channel_model.js:74:7)\n' +
    '    at /Users/maarten/ThisDot/starter.dev/starters/express-apollo-prisma/queue/worker.ts:33:17\n' +
    '    at Generator.next (<anonymous>)\n' +
    '    at /Users/maarten/ThisDot/starter.dev/starters/express-apollo-prisma/queue/worker.ts:31:71'
```

**Comment by mbicknese** [comment]
Initial work is done in

 - #1097
 - #1122

For ticket #1084
