### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by Kowiste** [thisdot/starter.dev#1326]
### What kit and version are you using?

nuxt 3 pinia vuetify

### What browser are you using?

firefox

### What operating system are you using?

ubuntu

### Actual Behavior

Im trying to use your starter with nuxt 3 vuetify, but the follow error:
```

Nuxi 3.3.1                                                                             15:53:02
Nuxt 3.3.1 with Nitro 2.3.3                                                            15:53:02
                                                                                       15:53:02
  > Local:    http://localhost:3000/ 
  > Network:  http://192.168.1.62:3000/
                                                                                       15:53:02

 ERROR  Cannot start nuxt:  The "name" argument must be specified                      15:53:02

  at new NodeError (node:internal/errors:393:5)
  at Performance.mark (node:internal/perf/performance:125:13)
  at normalizedModule (node_modules/nuxt/node_modules/@nuxt/kit/dist/index.mjs:168:30)
  at async installModule (node_modules/nuxt/node_modules/@nuxt/kit/dist/index.mjs:451:15)
  at async initNuxt (node_modules/nuxt/dist/index.mjs:2469:7)
  at async load (node_modules/nuxi/dist/chunks/dev.mjs:6843:9)
  at async Object.invoke (node_modules/nuxi/dist/chunks/dev.mjs:6873:5)
  at async _main (node_modules/nuxi/dist/cli.mjs:49:20)
```

I change with nvm to different version 16,18,19  but allways have the same error

### Expected Behavior

Should start nuxt dev

### Reproduction

- Use npx @this-dot/create-starter
- select nuxt 3 pinia vuetify
- enter in  the folder and run npm install

**Comment by Kowiste** [comment]
After look in multiple place I found this [https://github.com/nuxt/nuxt/issues/19682]()
To make it work you need  to update the nuxt dependency in package.json > "devDependencies":   from 3.3.1 to 3.3.2.
