### ISSUE TITLE
[angular-apollo-tailwind] Running yarn install on new project outputs error

### ISSUE THREAD

**Issue by dustinsgoodman** [thisdot/starter.dev#194]
# Bug Info

Running on a M1 mac

```
➜  ng-apollo-test node --version
v16.14.2
```

![Image](https://user-images.githubusercontent.com/1815379/174352836-50636743-09e7-40a4-8d4d-914d33e398a4.png)

```
warning Error running install script for optional dependency: "/Users/dustingoodman/development/starter-testing/ng-apollo-test/node_modules/nice-napi: Command failed.
Exit code: 1
Command: node-gyp-build
Arguments:
Directory: /Users/dustingoodman/development/starter-testing/ng-apollo-test/node_modules/nice-napi
Output:
gyp info it worked if it ends with ok
gyp info using node-gyp@8.4.1
gyp info using node@16.14.2 | darwin | arm64
gyp ERR! find Python
gyp ERR! find Python Python is not set from command line or npm configuration
gyp ERR! find Python Python is not set from environment variable PYTHON
gyp ERR! find Python checking if \"python3\" can be used
gyp ERR! find Python - \"python3\" is not in PATH or produced an error
gyp ERR! find Python checking if \"python\" can be used
gyp ERR! find Python - \"python\" is not in PATH or produced an error
gyp ERR! find Python
gyp ERR! find Python **********************************************************
gyp ERR! find Python You need to install the latest version of Python.
gyp ERR! find Python Node-gyp should be able to find and use Python. If not,
gyp ERR! find Python you can try one of the following options:
gyp ERR! find Python - Use the switch --python=\"/path/to/pythonexecutable\"
gyp ERR! find Python   (accepted by both node-gyp and npm)
gyp ERR! find Python - Set the environment variable PYTHON
gyp ERR! find Python - Set the npm configuration variable python:
gyp ERR! find Python   npm config set python \"/path/to/pythonexecutable\"
gyp ERR! find Python For more information consult the documentation at:
gyp ERR! find Python https://github.com/nodejs/node-gyp#installation
gyp ERR! find Python **********************************************************
gyp ERR! find Python
gyp ERR! configure error
gyp ERR! stack Error: Could not find any Python installation to use
gyp ERR! stack     at PythonFinder.fail (/Users/dustingoodman/.nvm/versions/node/v16.14.2/lib/node_modules/npm/node_modules/node-gyp/lib/find-python.js:330:47)
gyp ERR! stack     at PythonFinder.runChecks (/Users/dustingoodman/.nvm/versions/node/v16.14.2/lib/node_modules/npm/node_modules/node-gyp/lib/find-python.js:159:21)
gyp ERR! stack     at PythonFinder.<anonymous> (/Users/dustingoodman/.nvm/versions/node/v16.14.2/lib/node_modules/npm/node_modules/node-gyp/lib/find-python.js:202:16)
gyp ERR! stack     at PythonFinder.execFileCallback (/Users/dustingoodman/.nvm/versions/node/v16.14.2/lib/node_modules/npm/node_modules/node-gyp/lib/find-python.js:294:16)
gyp ERR! stack     at ChildProcess.exithandler (node:child_process:406:5)
gyp ERR! stack     at ChildProcess.emit (node:events:526:28)
gyp ERR! stack     at maybeClose (node:internal/child_process:1092:16)
gyp ERR! stack     at Socket.<anonymous> (node:internal/child_process:451:11)
gyp ERR! stack     at Socket.emit (node:events:526:28)
gyp ERR! stack     at Pipe.<anonymous> (node:net:687:12)
gyp ERR! System Darwin 21.5.0
gyp ERR! command \"/Users/dustingoodman/.nvm/versions/node/v16.14.2/bin/node\" \"/Users/dustingoodman/.nvm/versions/node/v16.14.2/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js\" \"rebuild\"
gyp ERR! cwd /Users/dustingoodman/development/starter-testing/ng-apollo-test/node_modules/nice-napi
✨  Done in 20.30s.
```

**Comment by ihardz** [comment]
Cannot reproduce on Windows. 
Possible fix: add **_.npmrc_** file into the project root with the following content:
for Windows:
`python=c:\Python31\python.exe`
for Mac: 
`python=/path/to/python27/python`

**Comment by dustinsgoodman** [comment]
Issue was that my local installation of python was corrupted. Not an issue with this project.
